### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TheConen** [TheConen/ttt_a3#6]
TODO:

- [x] Grundstruktur implementieren
- [ ] BW Loadouts an neue Truppstruktur anpassen
- [ ] US Loadouts komplett überarbeiten
- [ ] US Fahrzeuge erstellen und Loadouts überarbeiten
